package com.wp.ers.models;

import com.wp.ers.utilities.Utilities;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


// lombok annotations
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity // marks class as a table in our database
@Table(name = "reimbursements") // sets table name
@Component // marks the class as a Bean
public class Reimbursement {

    // create autogenerated primary field
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int reimbursementId;


    private String description;


    private float amount;

    @Enumerated(EnumType.STRING)
    private Utilities.Status status;


    // setup foreign key
    @ManyToOne
    @JoinColumn(name = "employee_id")
    private Employee employee;

    public String getDescription() {
        return description;
    }

    public Reimbursement(String description, float amount, Utilities.Status status, Employee employee) {
        this.description = description;
        this.amount = amount;
        this.status = status;
        this.employee = employee;
    }

// Getters & Setters


    public int getReimbursementId() {
        return reimbursementId;
    }

    public void setReimbursementId(int reimbursementId) {
        this.reimbursementId = reimbursementId;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public Utilities.Status getStatus() {
        return status;
    }

    public void setStatus(Utilities.Status status) {
        this.status = status;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }


}