package com.wp.ERS.models;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

// lombok annotations
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity // marks class as a table in our database
@Table(name = "employees") // sets table name
@Component // marks the class as a Bean
public class Employee {

    // enum for possible roles
    enum Role {
        associate,
        manager
    }

    // create autogenerated primary field
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int employeeId;

    @Column(nullable = false)
    private String firstName;

    @Column(nullable = false)
    private String lastName;

    @Column(nullable = false, unique = true)
    private String userName;

    @Column(nullable = false)
    private String password;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private Role role;
}