package com.wp.ers.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


// lombok annotations
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity // marks class as a table in our database
@Table(name = "reimbursements") // sets table name
@Component // marks the class as a Bean
public class Reimbursement {


    enum Status {
        pending,
        approved,
        denied
    }

    // create autogenerated primary field
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int reimbursementId;

    private String description;

    private Float amount;

    @Enumerated(EnumType.STRING)
    private Status status;

    // setup foreign key
    @ManyToOne
    @JoinColumn(name = "employee_id")
    private Employee employee;
}